name: Morpho Steckhouse Monitor

on:
  schedule:
    - cron: '0 7 * * *'  # Ogni giorno alle 9:00 italiane
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl bc

      - name: Leggi dati Morpho e aggiorna CSV
        run: |
          VAULT_ADDRESS="0x9a615cb3e9fa9e75070e5df5a75df6f2a75ed130"
          WALLET="0x6bD872Ef0749eBa102A9e7Cd9FC24Ed2A5C88679"
          DATE=$(date +'%Y-%m-%d')

          RESPONSE=$(curl -s -X POST https://api.morpho.org/graphql \
            -H "Content-Type: application/json" \
            -d '{
              "query": "query { vaultByAddress(address: \"'$VAULT_ADDRESS'\") { state { totalAssetsUsd totalSupply rewards { apr } allocation { market { state { supplyApr } } } } } }"
            }')

          BASE_APR=$(echo $RESPONSE | jq -r '.data.vaultByAddress.state.allocation.market.state.supplyApr')
          REWARD_APR=$(echo $RESPONSE | jq -r '.data.vaultByAddress.state.rewards[0].apr')
          APY=$(echo "$BASE_APR + $REWARD_APR" | bc -l)
          APY_DISPLAY=$(echo "$APY * 100" | bc -l | awk '{printf "%.2f", $0}')

          # Leggi saldo attuale
          BALANCE_RES=$(curl -s "https://api.llama.fi/protocol/morpho-blue")
          USD_VALUE=$(echo $BALANCE_RES | jq -r '.tvl')

          # Se c’è già un file, confronta con ieri
          PREV_BALANCE="0.00"
          if [ -f history.csv ]; then
            PREV_BALANCE=$(tail -n 1 history.csv | cut -d',' -f3)
          fi

          GAIN=$(echo "$USD_VALUE - $PREV_BALANCE" | bc -l | awk '{printf "%.2f", $0}')

          echo "$DATE,$APY_DISPLAY,$USD_VALUE" >> history.csv

          MSG="📊 *Morpho Steckhouse USDT – Report $DATE*\nSaldo: *$USD_VALUE USD*\nAPY: *$APY_DISPLAY%*\nProfitto da ieri: *$GAIN USD*"

          echo "$MSG"

          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.CHAT_ID }} \
            -d text="$MSG" \
            -d parse_mode="Markdown"

      - name: Commit aggiornamento storico
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add history.csv
          git commit -m "Aggiornamento storico $DATE" || echo "Nessuna modifica"
          git push
