name: Morpho Steakhouse Telegram

on:
  schedule:
    - cron: "0 7 * * *"  # ogni giorno alle 07:00 UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install requests
        run: pip install requests

      - name: Fetch Morpho vault data and notify Telegram
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python << 'EOF'
          import requests
          import os

          BOT_TOKEN = os.environ['BOT_TOKEN']
          CHAT_ID = os.environ['CHAT_ID']

          url = "https://api.morpho.org/graphql"
          query = """
          query {
            vault(id: "0xbEef047a543E45807105E51A8BBEFCc5950fcfBa") {
              name
              apy
              totalAssets
            }
          }
          """
          r = requests.post(url, json={"query": query})
          vault = r.json()["data"]["vault"]

          apy = float(vault["apy"]) * 100
          tvl = float(vault["totalAssets"]) / 1e6  # milioni di USDT

          message = (
              f"📊 Morpho - {vault['name']}\n"
              f"TVL: {tvl:.2f} M USDT\n"
              f"APY: {apy:.2f}%"
          )

          telegram_url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
          requests.post(telegram_url, json={"chat_id": CHAT_ID, "text": message})
          EOF
