name: Morpho Steakhouse Monitor

on:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Monitor Morpho and send Telegram alert
        shell: bash
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          set -e
          sudo apt-get update -qq && sudo apt-get install -y jq bc curl

          echo "=== Controllo PEG USDT ==="
          PEG=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=tether&vs_currencies=usd" | jq -r '.tether.usd')
          echo "PEG USDT: $PEG"

          echo "=== Controllo TVL Morpho ==="
          TVL=$(curl -s "https://api.llama.fi/protocol/morpho-blue" | jq -r '.tvl')
          echo "TVL Morpho: $TVL"

          SOGLIA_APY=4.0
          APY=5.2

          ALERTS=""
          if (( $(echo "$PEG < 0.995" | bc -l) )); then
            ALERTS="${ALERTS}⚠️ PEG USDT sotto 0.995 (attuale: $PEG)%0A"
          fi
          if (( $(echo "$APY < $SOGLIA_APY" | bc -l) )); then
            ALERTS="${ALERTS}⚠️ APY Morpho sceso a $APY%0A"
          fi

          REPORT="Monitoraggio Morpho/Steakhouse%0A\
USDT PEG: $PEG%0A\
TVL Morpho: $TVL USD%0A\
APY Morpho: ${APY}%%"

          if [ -n "$ALERTS" ]; then
            MSG="⚠️ ALLERTA%0A${ALERTS}%0A${REPORT}"
          else
            MSG="✅ Tutto OK%0A${REPORT}"
          fi

          echo "=== Invio messaggio Telegram ==="
          curl -s "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="$MSG" \
            -d parse_mode="Markdown"
