name: Morpho/Steakhouse Monitor

on:
  schedule:
    - cron: '0 8 * * *'   # 08:00 UTC
    - cron: '0 14 * * *'  # 14:00 UTC
    - cron: '0 20 * * *'  # 20:00 UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check Morpho & Send Telegram
        run: |
          sudo apt-get update && sudo apt-get install -y jq bc curl

          MSG=""

          echo "Controllo PEG USDT..."
          PEG=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=tether&vs_currencies=usd" | jq -r '.tether.usd')
          echo "PEG USDT: $PEG"
          if (( $(echo "$PEG < 0.995" | bc -l) )); then
            MSG="${MSG}⚠️ USDT PEG sotto 0.995 (attuale: $PEG)%0A"
          fi

          echo "Controllo TVL Morpho..."
          TVL=$(curl -s "https://api.llama.fi/protocol/morpho-blue" | jq -r '.tvl')
          echo "TVL Morpho: $TVL"
          MSG="${MSG}TVL Morpho: $TVL USD%0A"

          # Se vuoi anche un controllo APY puoi inserire manualmente una soglia
          SOGLIA_APY=4.0
          APY=5.2  # valore stimato, o puoi recuperarlo da un API personalizzata
          if (( $(echo "$APY < $SOGLIA_APY" | bc -l) )); then
            MSG="${MSG}⚠️ APY Morpho sceso a ${APY}%0A"
          else
            MSG="${MSG}APY Morpho: ${APY}%0A"
          fi

          if [ -z "$MSG" ]; then
            MSG="✅ Nessun problema rilevato su Morpho/Steakhouse."
          else
            MSG="Monitoraggio Morpho:%0A$MSG"
          fi

          echo "Invio messaggio Telegram..."
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.CHAT_ID }} \
            -d text="$MSG" \
            -d parse_mode="Markdown"
