name: Morpho/Steakhouse Monitor

on:
  schedule:
    - cron: '0 8 * * *'   # 08:00 UTC
    - cron: '0 14 * * *'  # 14:00 UTC
    - cron: '0 20 * * *'  # 20:00 UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check Morpho & Send Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          sudo apt-get update && sudo apt-get install -y jq bc curl

          # --- 1. Controllo PEG USDT ---
          PEG=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=tether&vs_currencies=usd" | jq -r '.tether.usd')
          echo "PEG USDT: $PEG"

          ALERTS=""
          if (( $(echo "$PEG < 0.995" | bc -l) )); then
            ALERTS="${ALERTS}⚠️ USDT PEG sotto 0.995 (attuale: $PEG)\n"
          fi

          # --- 2. Controllo TVL Morpho ---
          TVL=$(curl -s "https://api.llama.fi/protocol/morpho-blue" | jq -r '.tvl')
          echo "TVL Morpho: $TVL"

          # --- 3. Controllo APY (manuale o da API) ---
          SOGLIA_APY=4.0
          APY=5.2  # puoi sostituire questo valore con una chiamata API se disponibile
          if (( $(echo "$APY < $SOGLIA_APY" | bc -l) )); then
            ALERTS="${ALERTS}⚠️ APY Morpho sceso a ${APY}%\n"
          fi

          # --- 4. Componi messaggio finale ---
          REPORT="Monitoraggio Morpho/Steakhouse
USDT PEG: $PEG
TVL Morpho: $TVL USD
APY Morpho: ${APY}%"

          if [ -n "$ALERTS" ]; then
            FINAL_MSG="⚠️ ATTENZIONE\n${ALERTS}\n${REPORT}"
          else
            FINAL_MSG="✅ Tutto ok\n${REPORT}"
          fi

          echo "Messaggio finale:"
          echo -e "$FINAL_MSG"

          # --- 5. Invio a Telegram ---
          curl -s "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            --data-urlencode "text=${FINAL_MSG}" \
            -d parse_mode="Markdown"
