name: Morpho Steakhouse Monitor

on:
  schedule:
    # Orari UTC: 08:00, 14:00 e 20:00
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Monitor Morpho Steakhouse and send Telegram alert
        shell: bash
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          set -e
          sudo apt-get update -qq && sudo apt-get install -y jq bc curl

          echo "=== Controllo PEG USDT ==="
          PEG=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=tether&vs_currencies=usd" | jq -r '.tether.usd')
          echo "PEG USDT: $PEG"

          echo "=== Controllo TVL Steakhouse (Morpho) ==="
          # Query GraphQL a Morpho (usando l'indirizzo checksum corretto)
          TVL=$(curl -s 'https://blue-api.morpho.org/graphql' \
            -H 'Content-Type: application/json' \
            --data '{"query":"{ vault(id:\"0xbEef047a543E45807105E51A8BBEFCc5950fcfBa\") { totalSupplyAssets } }"}' \
            | jq -r '.data.vault.totalSupplyAssets')

          echo "TVL Steakhouse (USDT): $TVL"

          # APY atteso per controllare soglia
          SOGLIA_APY=4.0
          APY=5.2  # aggiorna se hai una fonte automatica

          ALERTS=""
          if (( $(echo "$PEG < 0.995" | bc -l) )); then
            ALERTS="${ALERTS}⚠️ PEG USDT sotto 0.995 (attuale: $PEG)%0A"
          fi

          if (( $(echo "$APY < $SOGLIA_APY" | bc -l) )); then
            ALERTS="${ALERTS}⚠️ APY Morpho sceso a $APY%0A"
          fi

          REPORT="Monitoraggio Morpho/Steakhouse%0AUSDT PEG: $PEG%0ATVL Steakhouse (USDT): $TVL%0AAPY Morpho: ${APY}%%"

          if [ -n "$ALERTS" ]; then
            MSG="⚠️ ALLERTA%0A${ALERTS}%0A${REPORT}"
          else
            MSG="✅ Tutto OK%0A${REPORT}"
          fi

          echo "=== Invio messaggio Telegram ==="
          curl -s "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="$MSG" \
            -d parse_mode="Markdown"
