name: Morpho Steakhouse Monitor

on:
  schedule:
    - cron: '0 8 * * *'   # 8 AM UTC
    - cron: '0 14 * * *'  # 2 PM UTC
    - cron: '0 20 * * *'  # 8 PM UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Monitor Morpho and send Telegram alert
        shell: bash
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SOGLIA_PEG: 0.995      # Configurable PEG threshold
          SOGLIA_APY: 4.0        # Configurable APY threshold
          SOGLIA_TVL: 1000000000 # Configurable TVL threshold ($1B)
        run: |
          set -e
          sudo apt-get install -y jq bc curl  # Install deps (update not needed)

          # Function to fetch with retry
          fetch_with_retry() {
            for i in {1..3}; do
              RESULT=$(curl -s --max-time 10 "$1") && [[ -n "$RESULT" ]] && echo "$RESULT" && return
              echo "Retry $i/3 for $1..." >&2
              sleep 2
            done
            echo "Failed to fetch $1" >&2
            exit 1
          }

          echo "=== Controllo PEG USDT ==="
          PEG_DATA=$(fetch_with_retry "https://api.coingecko.com/api/v3/simple/price?ids=tether&vs_currencies=usd")
          PEG=$(echo "$PEG_DATA" | jq -r '.tether.usd // 0')
          echo "PEG USDT: $PEG"

          echo "=== Controllo TVL Morpho ==="
          TVL=$(fetch_with_retry "https://api.llama.fi/tvl/morpho-blue")
          # Format TVL nicely (e.g., 3227019065 -> 3.23B)
          TVL_FORMATTED=$(echo "$TVL" | awk '{ if ($1 >= 1000000000) printf "%.2fB", $1/1000000000; else if ($1 >= 1000000) printf "%.2fM", $1/1000000; else printf "%.0f", $1 }')
          echo "TVL Morpho: $TVL_FORMATTED USD (raw: $TVL)"

          echo "=== Controllo APY Morpho ==="
          PROTOCOL_DATA=$(fetch_with_retry "https://api.llama.fi/protocol/morpho-blue")
          # Extract average APY (adjust jq path if needed; this assumes chain data has APY)
          APY=$(echo "$PROTOCOL_DATA" | jq -r '.chainTvls | to_entries | map(.value.apy) | add / length // 0')
          echo "APY Morpho: $APY%"

          ALERTS=""
          if (( $(echo "$PEG < $SOGLIA_PEG" | bc -l) )); then
            ALERTS="${ALERTS}⚠️ PEG USDT sotto $SOGLIA_PEG (attuale: $PEG)%0A"
          fi
          if (( $(echo "$APY < $SOGLIA_APY" | bc -l) )); then
            ALERTS="${ALERTS}⚠️ APY Morpho sceso a $APY%% (soglia: $SOGLIA_APY%%)%0A"
          fi
          if (( $(echo "$TVL < $SOGLIA_TVL" | bc -l) )); then
            ALERTS="${ALERTS}⚠️ TVL Morpho sotto $SOGLIA_TVL USD (attuale: $TVL_FORMATTED)%0A"
          fi

          REPORT="Monitoraggio Morpho/Steakhouse%0AUSDT PEG: $PEG%0ATVL Morpho: $TVL_FORMATTED USD%0AAPY Morpho: ${APY}%%"

          if [ -n "$ALERTS" ]; then
            MSG="⚠️ ALLERTA%0A${ALERTS}%0A${REPORT}"
          else
            MSG="✅ Tutto OK%0A${REPORT}"
          fi

          # Truncate if too long (unlikely now, but safety net)
          MSG=$(echo "$MSG" | cut -c1-4000)

          echo "=== Invio messaggio Telegram ==="
          RESPONSE=$(curl -s "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="$MSG" \
            -d parse_mode="Markdown")
          if [[ $RESPONSE != *'"ok":true'* ]]; then
            echo "Telegram send failed: $RESPONSE" >&2
            exit 1
          fi
          echo "Message sent successfully!"
