name: Portfolio Tracker

on:
  schedule:
    - cron: "0 6 * * *"  # Eseguito ogni giorno alle 06:00 UTC
  workflow_dispatch:      # Permette di avviarlo manualmente

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run portfolio tracker
        run: python portfolio_tracker.py
